# Generated by Django 5.1.4 on 2024-12-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('package_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='packages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
