# Generated by Django 5.1.4 on 2024-12-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='code',
        ),
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(max_length=100),
        ),
    ]
