# Generated by Django 5.1.4 on 2024-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('enquiry', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
