# Generated by Django 5.1.4 on 2024-12-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
