# Generated by Django 5.1.4 on 2024-12-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_tablepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepayment',
            name='expiry_date',
            field=models.CharField(max_length=7),
        ),
    ]
