# Generated by Django 5.1.4 on 2024-12-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_tablepayment_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablepayment',
            name='date_created',
        ),
        migrations.AddField(
            model_name='tablepayment',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.package'),
        ),
        migrations.AlterField(
            model_name='tablepayment',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
