# Generated by Django 5.1.4 on 2024-12-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_remove_tablepayment_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepayment',
            name='expiry_date',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='tablepayment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.package'),
        ),
    ]
