# Generated by Django 5.1.4 on 2025-01-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_tablepayment_number_of_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablepayment',
            name='number_of_people',
        ),
    ]
